# Numpy
## Definition

In [2]:
import numpy as np

Hope that you not see the error in command above. In other case you should download `numpy` with `pip` insturment. 

In [3]:
!pip install numpy# be careful with windows os. To install it inside Windows it very recomended to open console cmd.exe by yourself and write this command

^C


If you install numpy successfully lets continue. 

Numpy library is a library that contain convenient representation of multidimentional arrays. Or, more simple, the number of convenient functions for matrix with N dimensions.

The main difference from usual lists is numpy array has specified type and can contain only the elements of one type.

In [2]:
a = np.array ([1,2,3,4])
print (a)

[1 2 3 4]


In [11]:
b = np.array ([1,2,3,4.0])
print (b) #all elements is float

[1. 2. 3. 4.]


In [12]:
c = np.array ([1,2,3,'4'])
print (c) #all elements become characters

['1' '2' '3' '4']


In [6]:
d = np.array ([1,2,3.0,'d'])
print (d)

['1' '2' '3.0' 'd']


And for each array we can print its type

In [13]:
print (a.dtype, b.dtype, c.dtype, d.dtype)

int32 float64 <U11 <U32


<U11 mean UTF-8 and <U32 UTF-32. The list of all types you can see in documentation on site https://numpy.org/devdocs/user/basics.types.html

So, if we try to add into array an element of different type it will broke

In [19]:
a[1] = 1
print (a)
a[1] = '1' #numpy is smart enougth to convert char into number
print (a)
a[1] = 'a' #exception

[1 1 3]
[1 1 3]


ValueError: invalid literal for int() with base 10: 'a'

What more interesting - numpy arrays has fixied size, so after creating it you cannot append\insert\add element inside it, only change them or it construction

In [3]:
a.append(0)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

But there is method resize, that can you change the size of array. Still, try to not use it because to execute this command compiler need a big amount of time (for copy and creating a new memory cells)

In [4]:
a.resize (5)
print (a)

[1 2 3 4 0]


## Base

So, after a little introdaction into ndarray lets move to bases of numpy
Fisrt of all how we can create an array and what it actualy contain.

Hw we already discuss numpy is smart enoght to create an array from different data by transforming it. There are also some more useful commands. But we start from some additional useful information inside ndarray

In [5]:
a = np.array ([1,2,3,4])
b = np.array ([1,2,3,4], dtype = np.double)
print (a, b)

[1 2 3 4] [1. 2. 3. 4.]


Some variables that contain size parameters

In [9]:
print (a.ndim)# how many dimension we use: line - 1 dimension; matrix - 2 dimensions
print () 
c = np.array ([[1,2,3], [4,5,6]])
print (c)
c.ndim

1

[[1 2 3]
 [4 5 6]]


2

In [11]:
print (a.shape) #typle with one element write like (x,)
print (c.shape)

(4,)
(2, 3)


In [14]:
print (a.size)
print (c.size)

4
6


Now some function about types and size in memory

In [18]:
print (a.dtype)
b = np.array([1,2,3], dtype = np.double) # creating an array with fixed type
print (b.dtype)

int32
float64


In [19]:
print (a.itemsize) #how many bytes it take to store one element of array
print (b.itemsize)

4
8


## Creating of array

### By fullfill with elements
So, with the main way for creating an arrays you already met. No lets try some more interesting ways\hint to create an array

In [29]:
#one important point, you should put inside init of array the list of elements, not just elements
a = np.array(1,2,3,4,5,6) # not correct

TypeError: array() takes from 1 to 2 positional arguments but 6 were given

In [30]:
a = np.array ([1,2,3,4,5,6]) # correct

In [20]:
np.zeros ((2,2), dtype = np.int32) # array filled with zero elements

array([[0, 0],
       [0, 0]])

In [23]:
np.ones ((2,2,2), dtype = np.float)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [35]:
np.identity (4) # create the matrix with 1 at main diagonal and 0 in other elements

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

More generalized function

In [25]:
np.full ((3,2), 120, dtype = np.int64)

array([[120, 120],
       [120, 120],
       [120, 120]], dtype=int64)

### By using the already created array

And you can use already created array construction to construct new one

In [28]:
print (a)
print (np.full_like (a, 32))
print ()
print (b)
print (np.full_like (b, 32))
print ()
print (c)
print (np.full_like (c, 32))

[1 2 3 4]
[32 32 32 32]

[1. 2. 3.]
[32. 32. 32.]

[[1 2 3]
 [4 5 6]]
[[32 32 32]
 [32 32 32]]


In [46]:
print (np.repeat (a, 3)) # like a*3 for list
print ()
print (c)
print ()
print (np.repeat (c, 2)) # in default create a usual array with repeted elements of each array
print (np.repeat (c, 2, axis=0)) # mean repeat the arrays of array (0 axes, by lines)
print (np.repeat (c, 2, axis=1)) # mean repeat the element inside each array (1 axes, by column)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]

[[1 2 3]
 [4 5 6]]

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]
[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


### With range analog

And plus to this there is range analogs - arange (start, end, step) and linspace(start, end, number of elements between)

In [31]:
np.arange (1,10, 0.5) # with double step, yes)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [34]:
np.linspace (1,5,11) # fill array with evenly distributed elements

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

### Random values

Plus to all of this numpy can create an array with random elements from the box

In [47]:
np.random.rand (2,2) # random array with shape (2,2) with elements from 0 to 1

array([[0.43449641, 0.58308811],
       [0.9962799 , 0.82571491]])

In [59]:
print (np.random.randint (0, 1000)) # random number from a to b
print (np.random.randint (0, 1000, size =(2,2))) # fill the array (2,2) with random elements in range (0,1000)

498
[[171 489]
 [208 589]]


### Copy

And the last method - just copy array. Be careful, if you just write a = b you not copy the array, but create a new link to original one

In [60]:
a = np.array ([1,2,3,4])
b = a
b [1] = 10
print (a)

[ 1 10  3  4]


In [61]:
a = np.array ([1,2,3,4])
b = a.copy()
b [1] = 10
print (a)
print (b)

[1 2 3 4]
[ 1 10  3  4]


## Accessing elements

Another one interesting momnet inside numpy is accessing different element with a lot small hints, from accessing column by column to submatrix. So, lets begin

In [4]:
a = np.array ([[1,2,3], [4,5,6], [7,8,9]])

The first one is just access to one element with it indices

In [6]:
print (a[1][2]) # like in lists

6

In [7]:
print (a[1,2]) # indices as array, more convenient doen't it?

6


In [11]:
b = (1,2)
print (a[b]) # with tuple as indices

6


### Slices 

And of course we can slice a number of elements inside numpy array

In [13]:
print (a[0:2]) #like in usual array

[[1 2 3]
 [4 5 6]]


In [14]:
print (a[0:2][0:1]) # How you can see, here we only slice matrix into line, not elements by column

[[1 2 3]]


In [41]:
# For this purpose how you can guessd we use tuple
print (a[0:2,0:2])

a = np.random.randint (1, 1000, size = (4,4))
print ()
print (a)
print (a[1:3,1:3]) # take submatrix
print (a[:, 1:3]) # take only some columns

[[469 300]
 [ 85   1]]

[[538 175 863 420]
 [829 167 475  17]
 [318 642 691 714]
 [799 411 513 691]]
[[167 475]
 [642 691]]
[[175 863]
 [167 475]
 [642 691]
 [411 513]]


And we can use step parametr

In [28]:
print (a)


[[469 300 688 858]
 [ 85 311 229 389]
 [568 704  99 688]
 [769 810 229 265]]
[[469 688]
 [568  99]]


In [31]:
print (a[0,0:4:2])

[469 688]


In [32]:
print (a[0:4:2,0:4:2])

[[469 688]
 [568  99]]


### Replace

Also, you can replace subarray of your array with other array

In [43]:
print (a)
b = a.copy()

[[538 175 863 420]
 [829 167 475  17]
 [318 642 691 714]
 [799 411 513 691]]


In [39]:
a[1:3,1:3] = np.ones ((2,2))
print (a)

[[469 300 688 858]
 [ 85   1   1 389]
 [568   1   1 688]
 [769 810 229 265]]


But you should remember that the new array should have the same size as part that you want change

In [40]:
a[1:3,1:3] = np.ones ((3,3))

ValueError: could not broadcast input array from shape (3,3) into shape (2,2)

In [45]:
a = b.copy()
a[1:4:2,1:4:2] = np.ones ((2,2))
print (a)

[[538 175 863 420]
 [829   1 475   1]
 [318 642 691 714]
 [799   1 513   1]]


In [49]:
a = b.copy()
a[:,(0,1)] = np.ones((4,2)) # change only first two columns
print (a)

[[  1   1 863 420]
 [  1   1 475  17]
 [  1   1 691 714]
 [  1   1 513 691]]


In [50]:
a = b.copy()
a[(1,2),:] = np.ones((2,4)) # change only the second and third lines
print (a)

[[538 175 863 420]
 [  1   1   1   1]
 [  1   1   1   1]
 [799 411 513 691]]


### Array as index

Finaly we can use array as indices that we want get

In [63]:
print(a)

[[538 175 863 420]
 [  1   1   1   1]
 [  1   1   1   1]
 [799 411 513 691]]


In [61]:
c = [0,3,2]
print (a[c])

[[538 175 863 420]
 [799 411 513 691]
 [  1   1   1   1]]


In [92]:
c = [(0,3,2),(0,0,1)] # first array is coodrinates for x axes, second array for y axes
print (a[c])

c = list (zip(*[(0,3),(3,1),(0,2),(3,1)])) # for more convenience we create a pair of elements that we want and repack it with zip
print (a[c])

[538 799   1]
[420 411 863 411]


And we can use even boolean arrays as indices

In [93]:
a = b.copy()
print (a)

[[538 175 863 420]
 [829 167 475  17]
 [318 642 691 714]
 [799 411 513 691]]


In [99]:
c = np.ones ((4,4), dtype = np.bool)
c [(2,1,0,3), (1,2,0,1)] = 0
print (c)

a[c]# We take only the elements where the True

[[False  True  True  True]
 [ True  True False  True]
 [ True False  True  True]
 [ True False  True  True]]


array([175, 863, 420, 829, 167,  17, 318, 691, 714, 799, 513, 691])

In [103]:
a[c].reshape(4,3)

array([[175, 863, 420],
       [829, 167,  17],
       [318, 691, 714],
       [799, 513, 691]])

## Arithmetic

Unlike the standard python list numpy support fast arifmetic operation that work with each element inside array

In [3]:
a = np.array ([1,2,3])
a + 3

array([4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1])

In [5]:
a*3

array([3, 6, 9])

In [6]:
a/2

array([0.5, 1. , 1.5])

In [7]:
a//2

array([0, 1, 1], dtype=int32)

And you can made them even with other array

In [8]:
b = np.array ([4,5,6])
a+b

array([5, 7, 9])

In [14]:
a-b

array([-3, -3, -3])

In [10]:
print (a)
print (b)
a*b

[1 2 3]
[4 5 6]


array([ 4, 10, 18])

In [11]:
a/b

array([0.25, 0.4 , 0.5 ])

In [12]:
a//b

array([0, 0, 0], dtype=int32)

In [13]:
a**b #power

array([  1,  32, 729], dtype=int32)

However arrays should have same shapes

In [16]:
a = np.array ([[1,2],[3,4]])
b = np.array ([-1,0,1,2])
a +b 

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

Plus to this there are some more complicate function that can help to work with linear algebra

In [17]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [19]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [37]:
print (b)
np.abs(b)

[[ 0.76484219 -0.64421769]
 [ 0.64421769  0.76484219]]


array([[0.76484219, 0.64421769],
       [0.64421769, 0.76484219]])

In [28]:
a = np.array ([[1,2], [4,3]])
print (a)
print ()
print (np.max(a))
print (np.max(a, axis=1))# maximum in each line
print (np.max(a, axis=0))# maximum in each column

[[1 2]
 [4 3]]

4
[2 4]
[4 3]


In [35]:
a = np.array ([[1,2], [4,3]])
print (a)
print ()
print (np.min(a))
print (np.min(a, axis=1))# minimum in each line
print (np.min(a, axis=0))# minimum in each column

[[1 2]
 [4 3]]

1
[1 3]
[1 2]


In [36]:
a = np.array ([[1,2], [4,3]])
print (a)
print ()
print (np.sum(a))
print (np.sum(a, axis=1))# sum in each line
print (np.sum(a, axis=0))# sum in each column

[[1 2]
 [4 3]]

10
[3 7]
[5 5]


In [34]:
# rotation matrix
angel = 0.7
b = np.full ((2,2), angel)
print (b)
b[(0,1),(0,1)] = np.cos (b[(0,1),(0,1)]) #cos function in main diagonal
print (b)
b[(1,0),(0,1)] = np.sin (b[(1,0),(0,1)]) #sin function in secon diagonal
b [0,1] = -b[0,1]
print (b)

[[0.7 0.7]
 [0.7 0.7]]
[[0.76484219 0.7       ]
 [0.7        0.76484219]]
[[ 0.76484219 -0.64421769]
 [ 0.64421769  0.76484219]]


In [39]:
a = np.random.randint (1,10,(2,3))
b = np.random.randint (1,10,(3,2))
print (a)
print (b)
print()

print (np.matmul(a,b)) #multiple two matrix
print (np.matmul(b,a))

[[3 4 5]
 [1 8 8]]
[[1 8]
 [1 3]
 [5 4]]

[[32 56]
 [49 64]]
[[11 68 69]
 [ 6 28 29]
 [19 52 57]]


In [40]:
np.linalg.det (np.matmul(b,a)) # determinant

-2.557953848736364e-12

A lot more such operations you can find at https://docs.scipy.org/doc/numpy/reference/routines.linalg.html and https://docs.scipy.org/doc/numpy/reference/routines.math.html

Thank you for reading, until the next lecture)